### ISSUE TITLE
Creating a TS group for W4M

### ISSUE THREAD

**Issue by bgruening** [workflow4metabolomics/workflow4metabolomics#10]
Would it be good to create one group for all tools for W4M? For me it is hard to distinguish well maintained and less maintained metabolic tools - and I think with a W4M group this could be easier.

Thanks!
Bjoern

**Comment by lecorguille** [comment]
Ping @workflow4metabolomics

We already spoke about that during our last meeting

The ToolShed propose to display all the tools according to their owner's group : https://toolshed.g2.bx.psu.edu/groups

I guess that it's not a big deal to create a group. @martenson said, that we have just to request one.

One of the issue about those group is that are displaied all the tools of the group members. So if one people provides some tools that are not related to the group topic, they are also displaied. But currently, any of us (even me) is in this case.

So what do you think about that ?

Note that @bgruening from the IUC group and @martenson from the devteam (ToolShed developer) are in copy.

**Comment by bgruening** [comment]
ping @chcaron
What do you think about this?

**Comment by fgiacomoni** [comment]
ping @lecorguille, @bgruening, @chcaron 
We should have a login (e.g. fgiacomoni) associated with the w4m group and another one for more personal work (e.g. franckgiacomoni)... 
But Quid of multiple group participation ?

**Comment by lecorguille** [comment]
ping

My plan for other isolate tools (or NGS) is to push on tools-iuc or using my group name [abims](https://github.com/abims-sbr).

**Comment by chcaron** [comment]
Bjoern
I agree with the W4M TS Group option, which is complementary with the [W4M] tag to identify Metabolomics tools developped by W4M team.

**Comment by lecorguille** [comment]
ping @ethevenot @yguitton @mtremblayfr 

Any opposition, dear other members of the decision board? 😄 

(I guess my ping @workflow4metabolomics didn't work without a team level)

**Comment by ethevenot** [comment]
Fine for me. ET.

**Comment by yguitton** [comment]
Ok for me

Yann Guitton

Le 9 déc. 2016 18:35, "Etienne Thévenot" <notifications@github.com> a
écrit :

**Comment by mtremblayfr** [comment]
Fine for me, too

**Comment by lecorguille** [comment]
Ok, so thanks @bgruening to have relaunch this topic.
I will ask Martin Martenson to set a TS Group for **Workflow4Metabolomics** with

- melpetera
- ethevenot
- lecorguille
- mmonsoor
- fgiacomoni
- prog
- yguitton
- marie-tremblay-metatoul

If other members of W4M want to be in this TS Group (even if they aren't owner of a repository), let me know your id within the TS.

**Comment by bgruening** [comment]
Awesome thanks a bunch!
ping @martenson

**Comment by lecorguille** [comment]
Done: https://toolshed.g2.bx.psu.edu/groups#/175812cd7caaf439
