### ISSUE TITLE
API access to https://galaxy.workflow4metabolomics.org/

### ISSUE THREAD

**Issue by sneumann** [workflow4metabolomics/workflow4metabolomics#8]
Hi, I'd like to use API access to W4M, 
and have created an API key in https://galaxy.workflow4metabolomics.org/user/api_keys?cntrller=user&use_panels=True The client (using https://github.com/galaxyproject/bioblend) wants to access 
the Galaxy API (@pierrickrogermele knows :-) , but I get stuck at 
```
ConnectionError: Unexpected HTTP status code: 401: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Authorization Required</title>
</head><body>
<h1>Authorization Required</h1>
```

Either biobled needs to learn basic http authorization, or it is required that 
the `<Location /api>` of W4M is not included in the Basic Authorisation protection.

Yours, Steffen

**Comment by lecorguille** [comment]
Ping @chcaron @cduperier @fgiacomoni 

Yes it is a setting within the apache configuration.

By curiosity, what do you plan to do through the API?

**Comment by sneumann** [comment]
Hi, we are starting to unit-test workflows, see e.g. http://phenomenal-h2020.eu/jenkins/view/Integration%20tests/job/sample-workflow-test/ and others (currently mostly placeholders) in http://phenomenal-h2020.eu/jenkins/view/Integration%20tests/.
We aim to use https://github.com/phnmnl/wft4galaxy for the testing. 
Yours, Steffen

**Comment by chcaron** [comment]
Dear Steffen

currently we don't want to open the API for external access for "security" reasons. Opening programmatic accces from outside is not our priority because this is a production server, and we have to ensure stability of this instance and avoid the risk of (for example) flooding connections.

Regards
Christophe

**Comment by sneumann** [comment]
Ok, no problem. Yours, Steffen
