### ISSUE TITLE
 Creating a TS group for W4M

### ISSUE THREAD

**Issue by mtremblayfr** [workflow4metabolomics/workflow4metabolomics#9]
@bgruening
> Would it be good to create one group for all tools for W4M? For me it is hard to distinguish well maintained and less maintained metabolic tools - and I think with a W4M group this could be easier.

**Comment by lecorguille** [comment]
Ping @workflow4metabolomics 

We already spoke about that during our last meeting

The ToolShed propose to display all the tools according to their owner's group : https://toolshed.g2.bx.psu.edu/groups

I guess that it's not a big deal to create a group. @martenson said, that we have just to request one.

One of the issue about those group is that are displaied all the tools of the group members. So if one people provides some tools that are not related to the group topic, they are also displaied. But currently, any of us (even me) is in this case.

So what do you think about that ?

Note that @bgruening from the IUC group and @martenson from the devteam (ToolShed developer) are in copy.

**Comment by lecorguille** [comment]
See https://github.com/workflow4metabolomics/workflow4metabolomics/issues/10
